"""added patient registration and patient data tables

Revision ID: 709802001a63
Revises: 121fdbf19cc9
Create Date: 2024-07-30 11:11:30.822104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709802001a63'
down_revision = '121fdbf19cc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('gender', sa.String(length=80), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('contact', sa.String(length=80), nullable=False),
    sa.Column('next_of_kin', sa.String(length=80), nullable=False),
    sa.Column('next_of_kin_contact', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact')
    )
    op.create_table('patient_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('blood_pressure', sa.String(length=80), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('complaint', sa.String(length=255), nullable=False),
    sa.Column('diagnosis', sa.String(length=255), nullable=False),
    sa.Column('treatment', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_registration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_data')
    op.drop_table('patient_registration')
    # ### end Alembic commands ###
